language: cpp
sudo: false
matrix:
  include:
  - os: linux
    language: pyhton
    env: PYTHON=2.7 CPP_VERSION=11 GCC=4.8
    python: '2.7'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - deadsnakes
        - george-edison55-precise-backports
        packages:
        - g++-4.8
        - cmake
        - cmake-data
        - pkg-config
        - netcdf-bin
        - proj-bin
        - libnetcdf-dev
        - libproj-dev
        - libboost-all-dev
        - sqlite3
        - libgl1-mesa-dev
  - os: linux
    language: python
    env: PYTHON=3.4 CPP_VERSION=11 GCC=4.8
    python: '3.4'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - deadsnakes
        - george-edison55-precise-backports
        packages:
        - g++-4.8
        - cmake
        - cmake-data
        - pkg-config
        - netcdf-bin
        - proj-bin
        - libnetcdf-dev
        - libproj-dev
        - libboost-all-dev
        - sqlite3
        - libgl1-mesa-dev
  - os: linux
    language: python
    env: PYTHON=3.5 CPP_VERSION=11 GCC=4.8
    python: '3.5'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - deadsnakes
        - george-edison55-precise-backports
        packages:
        - g++-4.8
        - cmake
        - cmake-data
        - pkg-config
        - netcdf-bin
        - proj-bin
        - libnetcdf-dev
        - libproj-dev
        - libboost-all-dev
        - sqlite3
        - libgl1-mesa-dev
  - os: linux
    language: python
    env: PYTHON=3.6 CPP_VERSION=11 GCC=4.8
    python: '3.6'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - deadsnakes
        - george-edison55-precise-backports
        packages:
        - g++-4.8
        - cmake
        - cmake-data
        - pkg-config
        - netcdf-bin
        - proj-bin
        - libnetcdf-dev
        - libproj-dev
        - libboost-all-dev
        - sqlite3
        - libgl1-mesa-dev
cache:
  directories:
  - "$HOME/ibex"
  - "$HOME/ppl"
  - "$HOME/gmp"
  - "$HOME/vtk"
  - "$HOME/netcdf"
  - "$HOME/proj4"
notifications:
  email: false
before_install:
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex
- |
  # Configure build variables
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ -z "$GCC" ]; then export GCC=4.8; fi
    export CXX=g++-$GCC CC=gcc-$GCC;
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    export CXX=g++-$GCC CC=gcc-$GCC;
  fi
  if [ -n "$CPP_VERSION" ]; then export CPP_VERSION=-std=c++$CPP_VERSION; fi
  if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ "$PY" = "3" ]; then
        pip install --upgrade pip auditwheel twine;
      else
        pip install --user --upgrade pip auditwheel twine;
      fi
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update;
    brew install gcc48;
    if [ "$PY" = "3" ]; then
      brew install python$PY;
    else
      curl -fsSL -O https://bootstrap.pypa.io/get-pip.py;
      sudo -H python get-pip.py;
    fi
    pip$PY install --user --upgrade pip virtualenv auditwheel twine;
    python$PY -m virtualenv venv;
    source venv/bin/activate;
  fi
install:
- sh ./cmake/build_Ibex4pyIbex.sh
- sh ./cmake/build_ppl.sh
- sh ./cmake/build_VTK.sh
- sh ./cmake/build_netcdf.sh
- sh ./cmake/build_proj4.sh
script:
- cd ${TRAVIS_BUILD_DIR}
- echo ${TRAVIS_BUILD_DIR}
- mkdir -p build/build-release
- cd build/build-release
- cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DVTK_ROOT=${HOME}/vtk
  -DPPL_ROOT=${HOME}/ppl -DGMP_ROOT=${HOME}/gmp -DNETCDF_ROOT=${HOME}/netcdf -DPROJ4_ROOT=${HOME}/proj4
  -DPYBIND11_PYTHON_VERSION=$PYTHON -DPYBIND11_CPP_STANDARD=$CPP_VERSION -DCMAKE_BUILD_TYPE=RELEASE
  -DBUILD_TESTS=OFF -DWITH_PYTHON=ON -DWITH_3D=ON -DWITH_GRAPHIZ=OFF -DWITH_NETCDF=ON
  -DWITH_PYIBEX_VERSION=ON -DWITH_PPL=ON -DWITH_PROJ4=ON -DWITH_EXAMPLES=OFF ${TRAVIS_BUILD_DIR}
- make -j2
- make pip_package
deploy:
  provider: releases
  api_key:
    secure: Fun0CbX8ZNFwBhkvjNfYx07H7IzQACHrabfopimImqQM8FkPfiQqFFvcjsYe18MqB2+s0nqUsoas3JHzJ1zjOTlnhd6CkiEgIDH5I63WemzEKDaOU4F2LVNl5kgVdxnpcs2LNxKHgcMQfcK9gaAKp/qkHVsbHcxwpQ1kcX/XOF0KI7rEx4c97F+xCCn0rBiqO9PDBCSxpg1N7xGkVLpo5AZ7n53L3HO082awToyza4KvTZwWSITrV9w2CsNytFroLS8AGOXvstT5GUEWUBehu9HNQodcu3ZfIxZsPrqIhDe3kru59sF7j5hOuGuaWVYWjstCYyaQkGlkuF7LSAOhgG+9Iq1DUL2TIVMl0B9tTy/D14oaOPenLuogriuKdeQ0jQlbX6CTu5oiWLxKhc7j80VyFw8BG5vgJDpyGvM6iwpC6R1+ODnxY2FaYQqXxdPkStPZVL07ZKKlDd9Z2qQRkh6rBCl5yyuEmUijO6C/fSVo1Uo0lID1LHI7+yR9UWMJa9+cHF5VQ/y9jFvdNW3g5qK+xCfin9IRLr2EDR2FSuN4QmpJMC87VL0RWCnu3E243DeoM1Z79jWZYqnDnAj+HqZlAApUmui/ENKUkvmt8PpWpteq6HxG99LQ1ofNAyhKgHzFRdQs7M9+cWxbeV9sucq3/a5WkZGDcGuIoWtsi2M=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/build/build-release/pyinvariant-*.whl"
  skip_cleanup: true
  overwrite: true
  on:
    repo: ThomasLeMezo/invariant-lib
    # tags: true
