language: cpp
sudo: false
matrix:
  include:
  - os: linux
    language: pyhton
    env: PYTHON=2.7 CPP=11 GCC=4.8
    python: '2.7'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - deadsnakes
        - george-edison55-precise-backports
        packages:
        - g++-4.8
        - cmake
        - cmake-data
        - pkg-config
  - os: linux
    language: python
    env: PYTHON=3.4 CPP=11 GCC=4.8
    python: '3.4'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - deadsnakes
        - george-edison55-precise-backports
        packages:
        - g++-4.8
        - cmake
        - cmake-data
        - pkg-config
  - os: linux
    language: python
    env: PYTHON=3.5 CPP=11 GCC=4.8
    python: '3.5'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - deadsnakes
        - george-edison55-precise-backports
        packages:
        - g++-4.8
        - cmake
        - cmake-data
        - pkg-config
  - os: linux
    language: python
    env: PYTHON=3.6 CPP=11 GCC=4.8
    python: '3.6'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kubuntu-backports
        - deadsnakes
        - george-edison55-precise-backports
        packages:
        - g++-4.8
        - cmake
        - cmake-data
        - pkg-config
  - os: osx
    env: PYTHON=2.7 CPP=14 CLANG
  - os: osx
    env: PYTHON=3.6 CPP=14 CLANG
  - os: osx
    env: PYTHON=3.5 CPP=14 CLANG
cache:
  directories:
  - "$HOME/ibex"
notifications:
  email: false
before_install:
- bash ./cmake/build_Ibex4pyIbex.sh
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex
- |
  # Configure build variables
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ -z "$GCC" ]; then export GCC=4.8; fi
    export CXX=g++-$GCC CC=gcc-$GCC;
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    export CXX=clang++ CC=clang;
  fi
  if [ -n "$CPP" ]; then export CPP=-std=c++$CPP; fi
  if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ "$PY" = "3" ]; then
        python -m pip install --user --upgrade pip;:
        python -m pip install --user auditwheel==1.4 twine;
      else
        python -m pip install --user --upgrade pip;
        python -m pip install --user auditwheel==1.4 twine;
      fi
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    if [ "$PY" = "3" ]; then
      brew update; brew install python$PY;
    else
      curl -fsSL -O https://bootstrap.pypa.io/get-pip.py;
      sudo -H python get-pip.py;
    fi
    pip$PY install --user --upgrade pip virtualenv auditwheel==1.4 twine;
    python$PY -m virtualenv venv;
    brew install llvm;
    source venv/bin/activate;
  fi
install:
- sh ./cmake/build_Ibex4pyIbex.sh
script:
- mkdir -p build/build-release
- cd build/build-release
- cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DPYTHON_VERSION=${version}
  -DPYBIND11_PYTHON_VERSION=$PYTHON -DPYBIND11_CPP_STANDARD=$CPP -DCMAKE_BUILD_TYPE=RELEASE
  -DBUILD_TESTS=OFF -DWITH_PYTHON=ON -DWITH_3D=OFF -DWITH_GRAPHIZ=OFF -DWITH_NETCDF=OFF
  -DWITH_PYIBEX_VERSION=ON -DWITH_EXAMPLES=OFF ../..
- make -j2
- make pip_package
- export wheel_file=$(ls *.whl)
- echo $wheel_file
- auditwheel repair $wheel_file
# - auditwheel repair ${wheel_file}
# - mkdir -p $TRAVIS_BUILD_DIR/wheelhouse
# - mv $wheel_file $TRAVIS_BUILD_DIR/wheelhouse
# - echo $TRAVIS_BUILD_DIR
- ls $TRAVIS_BUILD_DIR/build/build-release

deploy:
  provider: releases
  api_key:
    secure: NAXVYKKCCBMzCaHEsF9miYaKUMl2H7RZoniXdXx8de96emKsB8MHL2ItqJB+H8MaIr/h68f5KX4614oi6I3LLvI+H7V9clJ77sDR87ZMPmo/LX0rViW3Ijh4ZQ123xw+jtNJCBk9rON8TNNxM9CKmfrEdZjTM+S/48gqcFYDZdCMIPRAJolD2SPGT2eMx3PzKk8OW9te97QjIpRuG67KXV78zet5XGdhp9mQ6DMA+453XiyHb3rh26c9qGm9SFAQstLv0/OfOJ/GaZAKA1toUiJbnk2OAUhI0QUXIMhKH/fZzzajJTfr4rOL2CtDDp677cWmubqctPc8gfXBmu4hI9HV2+vtp7Gj0XP/NkUgv0zYjSnz929saFJ+dHpl3XenxIJkUj7coU8oDzsoKX/Uz5/yNCY1LXZvt7lAKa8j//qpMYUXfSTblSdClSnQ5oGG7nhpPlXVU90GLai1ACR3rI6CFeyuOZlZAG0OcpVA37pQJ18Zl+BIeR6Jsbu0FO3YQ/udQ0mC71++yXFpYnOExFNPAYd/na+JDaDQKf34/GK6x2z4/5qMaivjAtE65Og/ImzejOmw/pwmS47xOxfPRYnkeuSIxi/7a91vujqowIyhGk61knez4xOGlYzAAPG/u0zXVRY99gqVmzfZzcftc/flnyCzuZu4una1P0Pqalw=
  file_glob: true
  file: $TRAVIS_BUILD_DIR/build/build-release/pyinvariant-*.whl
  skip_cleanup: true
  overwrite: true
  on:
    repo: ThomasLeMezo/invariant-lib
    # tags: true
