# ==================================================================
#  invariant-lib - travis test script
# ==================================================================

language: cpp
sudo: false
matrix:
  include:
  - os: linux
    language: pyhton
    env: PYTHON=2.7 CPP=11 GCC=4.8
    python: "2.7"
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes, george-edison55-precise-backports]
        packages: [g++-4.8, cmake, cmake-data, pkg-config]
  - os: linux
    language: python
    env: PYTHON=3.4 CPP=11 GCC=4.8
    python: "3.4"
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes, george-edison55-precise-backports]
        packages: [g++-4.8, cmake, cmake-data, pkg-config]
  - os: linux
    language: python
    env: PYTHON=3.5 CPP=11 GCC=4.8
    python: "3.5"
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes, george-edison55-precise-backports]
        packages: [g++-4.8, cmake, cmake-data, pkg-config]
  - os: linux
    language: python
    env: PYTHON=3.6 CPP=11 GCC=4.8
    python: "3.6"
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, kubuntu-backports, deadsnakes, george-edison55-precise-backports]
        packages: [g++-4.8, cmake, cmake-data, pkg-config]

  - os: osx
    osx_image: xcode7.3
    env: PYTHON=2.7 CPP=14 CLANG
  - os: osx
    osx_image: xcode7.3
    env: PYTHON=3.6 CPP=14 CLANG
  - os: osx
    osx_image: xcode7.3
    env: PYTHON=3.5 CPP=14 CLANG

cache:
  directories:
  - $HOME/ibex

notifications:
  email: false
    # on_success: never
    # on_failure: never

before_install:
  # - if [ $TRAVIS_OS_NAME == linux ]; then python -m pip install auditwheel twine; fi
  # - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install python3; fi
  # - if [ $TRAVIS_OS_NAME == osx ]; then pip install --user wheel twine; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew install clang-omp; fi
  - bash ./cmake/build_Ibex4pyIbex.sh
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex
  - |
    # Configure build variables
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ -z "$GCC" ]; then export GCC=4.8; fi
      export CXX=g++-$GCC CC=gcc-$GCC;
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      export CXX=clang++ CC=clang;
    fi
    if [ -n "$CPP" ]; then export CPP=-std=c++$CPP; fi
    if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        if [ "$PY" = "3" ]; then
          pip install --upgrade pip auditwheel twine;
        else
          pip install --user --upgrade pip auditwheel twine;
        fi
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      if [ "$PY" = "3" ]; then
        brew update; brew install python$PY;
      else
        curl -fsSL -O https://bootstrap.pypa.io/get-pip.py;
        sudo -H python get-pip.py;
      fi
      pip$PY install --user --upgrade pip virtualenv auditwheel twine;
      python$PY -m virtualenv venv;
      source venv/bin/activate;
    fi


#before_install:
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install clang-omp; fi

install:
  - sh ./cmake/build_Ibex4pyIbex.sh
  # - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex/share/pkgconfig

script:
  - mkdir -p build/build-release
  - cd build/build-release
  - cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTS=OFF -DWITH_PYTHON=ON -DWITH_3D=OFF -DWITH_GRAPHIZ=OFF -DWITH_NETCDF=OFF -DWITH_PYIBEX_VERSION=ON -DWITH_EXAMPLES=OFF ../..
  - make -j2
  - make pip_package
  - export wheel_file=$(ls *.whl)
  - auditwheel repair $wheel_file
  - mv $wheel_file $TRAVIS_BUILD_DIR/$wheel_file